name: Pipeline Ejecutor de Pruebas QA

# ¿Cuándo se activa?: Cada vez que hagamos un 'git push' a la rama main
on:
  push:
    branches: [ "main" ]

jobs:
  ejecutar-tests:
    # El entorno: Le pedimos a GitHub una máquina limpia con Linux Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Descargar el código del repositorio
    - name: Descargar codigo del repositorio
      uses: actions/checkout@v4

    # Paso 2: Instalar y configurar Python
    - name: Configurar Python en el servidor
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Paso 3: Instalar las dependencias (requests, pytest, playwright, etc.)
    - name: Instalar dependencias de QA
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Paso 4: NUEVO - Descargar los navegadores headless dentro de la máquina de GitHub
    - name: Instalar Navegadores de Playwright
      run: playwright install --with-deps

    # Paso 5: Dejar que pytest ejecute TODO (API y WEB) de forma consecutiva
    - name: Ejecutar Test Suite con Pytest
      run: |
        pytest -v
